dist: trusty
language:
  - cpp
compiler:
  - gcc
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
before_install:
    - eval "${MATRIX_EVAL}"
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG -DHJSON_ENABLE_TEST=ON .. && make runtest
