language: cpp
jobs:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9.2
      env:
         - MATRIX_EVAL="CC=gcc-9.2 && CXX=g++-9.2"
    - os: osx
      compiler: clang
    - os: windows
      env:
        - GENERATOR="Visual Studio 15 2017 Win64"
        - ARTIFACT=vs2017-64bit
before_install:
    - eval "${MATRIX_EVAL}"
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG -DHJSON_ENABLE_TEST=ON .. && cmake --build . --target runtest
